[package]

name = "rust-2048"
version = "0.0.0"
authors = ["coeuvre <coeuvre@gmail.com>"]

[[bin]]

name = "rust-2048"
path = "src/main.rs"

[dependencies]
rustc-serialize = "0.3"
rand = "0.3.7"
piston_window = "0.56.0"
pistoncore-sdl2_window = "0.36.0"
piston2d-opengl_graphics = "0.35.0"
